version: '3'
services:
  maestro:
    image: mysql:5.7
    container_name: maestro
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: replica
    ports:
      - "3008:3306"
    command: --server-id=1 --log-bin=mysql --binlog-do-db=replica
    volumes:
      - maestro-data:/var/lib/mysql

  mysql_esclavo:
    image: mysql:5.7
    container_name: mysql_esclavo
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: replica
    ports:
      - "3009:3306"
    command: --server-id=2 --relay-log=mysql-relay-bin --log-bin=mysql --binlog-do-db=replica
    depends_on:
      - maestro
    volumes:
      - esclavo-data:/var/lib/mysql

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: maestro:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: replica
    ports:
      - "8082:80"
    depends_on:
      - maestro

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: maestro:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: replica
    ports:
      - "8083:80"
    depends_on:
      - maestro

  wordpress3:
    image: wordpress:latest
    container_name: wordpress3
    environment:
      WORDPRESS_DB_HOST: maestro:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: replica
    ports:
      - "8084:80"
    depends_on:
      - maestro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: maestro,mysql_esclavo
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - maestro
      - mysql_esclavo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

volumes:
  maestro-data:
  esclavo-data:
